name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0-alpha+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.16.0
  percent_indicator: ^4.0.1
  file_picker: ^8.3.3
  dotted_border: ^2.1.0
  shared_preferences: ^2.5.2
  http: ^1.3.0
  flutter_client_sse: 2.0.3
  flutter_markdown: ^0.7.3
  fetch_client: ^1.0.2
  supabase_flutter: ^2.12.4
  line_awesome_flutter: ^3.0.1
  animate_do : ^5.1.0
  flutter_multi_select_items: ^0.4.3
  flutter_file_downloader: ^2.1.1
  open_filex: ^4.3.2
  carousel_slider: ^5.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  lottie: ^3.3.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#441F7F"
  image: lib/assets/pictures/logo-png.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/pictures/logo-full.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - lib/assets/alurHCI.png
    - lib/assets/baganHCI.png
    - lib/assets/iconjpg.png
    - lib/assets/iconpdf.png
    - lib/assets/rocket.png
    - lib/assets/check.png
    - lib/assets/1st.png
    - lib/assets/2nd.png
    - lib/assets/3rd.png
    - lib/assets/empty.png
    - lib/assets/starempty.png
    - lib/assets/starfilled.png
    - lib/assets/learnbg.png
    - lib/assets/pictures/background-pattern.png
    - lib/assets/pictures/background-pattern-L.png
    - lib/assets/pictures/dashboard.png
    - lib/assets/pictures/imk-picture.jpg
    - lib/assets/pictures/splash.png
    - lib/assets/vectors/welcome_primary.png
    - lib/assets/vectors/levely_smile.svg
    - lib/assets/vectors/levely_thinking.svg
    - lib/assets/vectors/levely_error.svg
    - lib/assets/vectors/levely_new_chat.svg
    - lib/assets/vectors/levely_empty_chat.svg
    - lib/assets/vectors/artlover-secondary.svg
    - lib/assets/vectors/designergirl-secondary.svg
    - lib/assets/vectors/gameday-secondary.svg
    - lib/assets/vectors/gaming-primary.svg
    - lib/assets/vectors/gaming-secondarysvg.svg
    - lib/assets/vectors/onlineart-secondary.svg
    - lib/assets/vectors/socialinfluencer-primary.svg
    - lib/assets/vectors/socialshare-primary.svg
    - lib/assets/vectors/winterdesign-secondary.svg
    - lib/assets/vectors/socialshare-primary.png
    - lib/assets/vectors/socialinfluencer-primary.png
    - lib/assets/vectors/gaming-primary.png
    - lib/assets/vectors/learn.png
    - lib/assets/pictures/background-pattern.png
    - lib/assets/pictures/background-pattern-L.png
    - lib/assets/pictures/icon.png
    - lib/assets/pictures/logo-full.png
    - lib/assets/pictures/logo-png.png
    - lib/assets/pictures/about-header.png
    - lib/assets/pictures/about-logo.png
    - lib/assets/pictures/docker.png
    - lib/assets/pictures/flutter.png
    - lib/assets/pictures/mysql.png
    - lib/assets/pictures/node.png
    - lib/assets/pictures/react.png
    - lib/assets/pictures/supabase.png
    - lib/assets/badges/beginner.png
    - lib/assets/badges/basic_understanding.png
    - lib/assets/badges/developing_learner.png
    - lib/assets/badges/intermediate.png
    - lib/assets/badges/proficient.png
    - lib/assets/badges/advanced.png
    - lib/assets/badges/master.png
    - lib/assets/pixels/assessment-pixel.png
    - lib/assets/pixels/assignment-pixel.png
    - lib/assets/pixels/check.png
    - lib/assets/pixels/lock-pixel.png
    - lib/assets/pixels/material-pixel.png
    - lib/assets/pixels/star.png
    - lib/assets/pixels/time-pixel.png
    - lib/assets/leaderboards/banner-bronze.png
    - lib/assets/leaderboards/banner-bronze-vertical.png
    - lib/assets/leaderboards/banner-gold.png
    - lib/assets/leaderboards/banner-gold-vertical.png
    - lib/assets/leaderboards/banner-silver.png
    - lib/assets/leaderboards/banner-silver-vertical.png
  fonts:
    - family: DIN_Next_Rounded
      fonts:
        - asset: lib/assets/fonts/DIN_Next_Rounded_Regular.ttf
    - family: Modak
      fonts:
        - asset: lib/assets/fonts/Modak-Regular.ttf
