# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

def flutter_install_all_ios_pods(ios_application_path = nil)
  native_additions_path = File.join(ios_application_path, 'Flutter', 'flutter_export_environment.sh')
  return unless File.exist?(native_additions_path)

  File.foreach(native_additions_path) do |line|
    matches = line.match(/\Aexport\s+(.+)=(.*)\z/)
    next unless matches
    key = matches[1]
    value = matches[2].gsub(/\A"(.*)"\z/, '\1')
    ENV[key] = value
  end

  podhelper_path = File.join(File.expand_path(File.dirname(__FILE__)), 'Flutter', 'podhelper.rb')
  require podhelper_path
  install_all_flutter_pods(ios_application_path)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
