name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
          add-to-path: false

      - name: Fix CMake Permissions for Cache
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/cmake/
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/cmake/

      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/cmake/
          key: ${{ runner.os }}-cmake-3.22.1

      - name: Cache Android SDK Platform 33
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/platforms/android-33
          key: ${{ runner.os }}-android-sdk-33

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/hosted
            ~/.pub-cache/git
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Clean Flutter
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Setup Keystore
        run: |
          echo "${{ secrets.PLAY_STORE_UPLOAD_KEY }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: APK Upload
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:647460537786:android:e525a74d6979a72ca98983
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers, #students
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
